### PR TITLE
multiple approval policies

### PR DESCRIPTION
**Pull request by mspiegel**
This is the basic implementation of multiple approval policies. The following approval match policies have been implemented: "anyone", "people", "org-delegate", "org-quorum", "and", "or", "true", "false". The default match policy is "people".
    
The approval policies have unit tests!
    
(Controversially?) The .lgtm file has been reformatted from TOML to JSON. The TOML parsers are either buggy and/or feature-incomplete when compared to encoding/json. We can revisit this decision it's not hard to change the serde glue.
    
I've also reorganized the .lgtm file so that has several major sections. The previous style of lots of top-level key/value pairs is confusing. In an uncoming commit I'll rename the file from ".lgtm" to ".lgtmeow". Renaming the file will emphasize that the new file has a different format than the old file.
    
Approval scopes have not yet been implemented. A scope can limit an approval policy to specific
git branches or specific file paths. Implementing scopes is the next item on the agenda.
    
I've downgraded the lgtmeow version number from 1.0.0 to 0.5.0. This is to indicate that we're doing some big changes and major design decisions are in flux.
    
The lgtmeow.github.io documentation will need to be updated. Conveniently there is a separate ticket already for updating documentation. The Golang comments in model/approval.go are a good start for explaining the policies.

### CODE REVIEW

**Comment by mspiegel** [comment]
Approval scopes have been implemented. Scopes are currently applied only on the pull request base branch. TBD is applying scope based on file paths as well.

**Comment by mspiegel** [comment]
HJSON support will be added to this pull request. Then it will be feature complete.

**Comment by mspiegel** [comment]
Added HJSON support. The library that supports HJSON is a little hacky. It unmarshals HJSON to an untyped map[string]{interface}. So we unmarhsal it to an intermediate object. Then marshal it into JSON and then from JSON to the actual typed object.

**Comment by mspiegel** [comment]
This pull request is now feature complete

**Comment by jonbodner** [comment]
Do we have a default approval policy in place if the user specifies rules that don't match the current branch being merged? I'm looking at this code in particular:
```go
func approvalPolicy(req ApprovalRequest) *ApprovalPolicy {
	for _, approval := range req.Config.Approvals {
		if matchesScope(req, &approval.Scope) {
			return approval
		}
	}
	panic("Final approval policy must always match scope")
}
```

We should probably get rid of panics like this, since they will take down the entire lgtmeow server.

**Comment by jonbodner** [comment]
Approving it, can address these questions in another PR.

**Pull request merged**
