### PR TITLE
Reorganize "version" section of lgtmeow configuration file.

### PR DESCRIPTION
**Pull request by mspiegel**
- Rename "version" section to "tag". In my experience when I first encountered the version section I misunderstood its function. I believed it somehow pushed artifacts to an artifact management system like nexus, npm, artifactory, etc. IMO renaming the section highlights its purpose.
- Declare three algorithm types: "semver", "timestamp-millis", and "timestamp-rfc3339". This allows the "tsformat" field to be deleted. Its possible that collapsing all the configuration into the algorithm field will not scale if we need to add dozens of algorithms in the future. I'd rather eliminate "tsformat" for now and then wait and see what use cases are requested.
- Change the default regular expression from `(?i)^LGTM\s*(\S*)` to `(?i)^LGTM\s*(?P<version>\S*)` Using a named capture group allows groups to be arbitrarily reordered.
- Declare a new property "template" in the tag section. This allows a Golang template to be defined for the tagging. Default value is "{{.Version}}". Allows repositories to supply their own prefixes and suffixes for tagging.
- Add optional tag section to approval policies. If the tag section is defined in a policy, then that tag section is used when the approval scope matches (ie the specified git branches). If no tag section is defined then fallback to the global tag section.

### CODE REVIEW

**Comment by jonbodner** [comment]
```
jon@Hagrid ~/go-projects/src/github.com/lgtmeow/lgtmeow $ make test
go tool vet -shadow=true ./cache ./api ./remote ./version ./store ./shared ./model ./notifier ./hjson ./router ./set ./web
remote/github/client.go:120: declaration of "err" shadows declaration at remote/github/client.go:110
web/login.go:57: declaration of "err" shadows declaration at web/login.go:33
web/login.go:69: declaration of "err" shadows declaration at web/login.go:33
make: *** [vet] Error 1
```

I'll fix this locally and check it in.

**Comment by jonbodner** [comment]
One minor-ish thing that I'm changing (maybe it's just fiddling, but I can justify it): I want to make web/tag.go:17 (generateTag) into a method on TagConfig that takes in a model.TemplateTag. This way we make explicit what fields are allowed in the template, because they will be the fields on TemplateTag.

**Comment by jonbodner** [comment]
I found a couple of places where we were importing from `lgtmco/lgtm` still. I've removed them and run a `glide up -u -s -v`. There was also some minor go fmt stuff to run.

**Comment by mspiegel** [comment]
Thanks for catching those. I hadn't upgraded to go 1.7 and now "go vet" is catching those errors. The "lgtmco" imports somehow mysteriously show up whenever I regenerate the mock files. It will be good when we rip out the mock package. I just blew away my entire /pkg directory I wonder if that will help.

**Pull request merged**
